name: iot_baby_watch
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  freezed_annotation: ^2.4.4
  talker_flutter: ^4.1.3
  talker_dio_logger: ^4.1.3
  talker_bloc_logger: ^4.1.3
  injectable: ^2.4.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  rx_shared_preferences: ^4.0.0
  auto_route: ^9.2.2
  flutter_native_splash: ^2.4.1
  flutter_dotenv: ^5.1.0
  result_dart: ^1.1.1
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  google_sign_in: ^6.2.1
  pin_code_fields: ^8.0.1
  pretty_animated_buttons: ^0.0.2
  animated_text_kit: ^4.2.2
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  dio: ^5.7.0
  multi_state_bloc: ^0.0.4
  skeleton_loader: ^2.0.0+4
  toggle_switch: ^2.3.0
  sliding_switch: ^1.1.0
  animated_toggle_switch: ^0.8.3
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  audioplayers: ^6.1.0
  firebase_database: ^11.1.5
  firebase_messaging: ^15.1.4
  firebase_auth: ^5.3.2
  flutter_local_notifications: ^18.0.1
  cached_network_image: ^3.4.1
  flutter_layout_grid: ^2.0.7
  flutter_inappwebview: ^6.1.5
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  freezed: ^2.5.2
  injectable_generator: ^2.4.2
  flutter_gen_runner: ^5.4.0
  intl_utils: ^2.8.7
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true
    flare_flutter: false

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter_intl:
  enabled: true
  main_locale: "en"
  arb_dir: assets/l10n
