// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUgCNpVCrF8Ewg4aBQSj8pKnXDoIsfDRs',
    appId: '1:866121474427:android:181f9fb9e01c25e8ba5dde',
    messagingSenderId: '866121474427',
    projectId: 'pbl6-519c3',
    databaseURL: 'https://pbl6-519c3-default-rtdb.firebaseio.com',
    storageBucket: 'pbl6-519c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByU0ZlTcaM2kmuEnPk1jUv9sAVcklK9Dw',
    appId: '1:866121474427:ios:12b61e6ab3d5d5b8ba5dde',
    messagingSenderId: '866121474427',
    projectId: 'pbl6-519c3',
    databaseURL: 'https://pbl6-519c3-default-rtdb.firebaseio.com',
    storageBucket: 'pbl6-519c3.appspot.com',
    iosBundleId: 'com.example.iotBabyWatch',
  );
}
